# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user_info', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='integer_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
